/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Solver_constr_h_fun_jac_uxt_zt_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s3[3] = {0, 0, 0};
static const casadi_int casadi_s4[121] = {117, 1, 0, 117, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116};
static const casadi_int casadi_s5[63] = {8, 12, 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 2, 3, 4, 7, 2, 3, 4, 7, 2, 3, 4, 7, 2, 3, 4, 7, 2, 3, 4, 7, 2, 3, 4, 7, 2, 3, 4, 7, 2, 3, 4, 7, 2, 3, 4, 7, 2, 3, 4, 7, 2, 3, 4, 7, 2, 3, 4, 7};
static const casadi_int casadi_s6[12] = {8, 8, 0, 0, 0, 0, 0, 1, 1, 1, 1, 4};
static const casadi_int casadi_s7[3] = {12, 0, 0};

/* Solver_constr_h_fun_jac_uxt_zt_hess:(i0[6],i1[2],i2[12],i3[],i4[117])->(o0[12],o1[8x12,48nz],o2[8x8,1nz],o3[12x0],o4[]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a4, a5, a6, a7, a8, a9;
  a0=arg[4]? arg[4][81] : 0;
  a1=arg[0]? arg[0][0] : 0;
  a2=arg[0]? arg[0][2] : 0;
  a3=cos(a2);
  a4=arg[4]? arg[4][80] : 0;
  a3=(a3*a4);
  a1=(a1+a3);
  a3=(a0*a1);
  a5=arg[4]? arg[4][82] : 0;
  a6=arg[0]? arg[0][1] : 0;
  a7=sin(a2);
  a7=(a7*a4);
  a6=(a6+a7);
  a7=(a5*a6);
  a3=(a3+a7);
  a7=arg[4]? arg[4][83] : 0;
  a8=arg[0]? arg[0][5] : 0;
  a7=(a7+a8);
  a3=(a3-a7);
  if (res[0]!=0) res[0][0]=a3;
  a3=arg[4]? arg[4][84] : 0;
  a7=(a3*a1);
  a9=arg[4]? arg[4][85] : 0;
  a10=(a9*a6);
  a7=(a7+a10);
  a10=arg[4]? arg[4][86] : 0;
  a10=(a10+a8);
  a7=(a7-a10);
  if (res[0]!=0) res[0][1]=a7;
  a7=arg[4]? arg[4][87] : 0;
  a10=(a7*a1);
  a11=arg[4]? arg[4][88] : 0;
  a12=(a11*a6);
  a10=(a10+a12);
  a12=arg[4]? arg[4][89] : 0;
  a12=(a12+a8);
  a10=(a10-a12);
  if (res[0]!=0) res[0][2]=a10;
  a10=arg[4]? arg[4][90] : 0;
  a12=(a10*a1);
  a13=arg[4]? arg[4][91] : 0;
  a14=(a13*a6);
  a12=(a12+a14);
  a14=arg[4]? arg[4][92] : 0;
  a14=(a14+a8);
  a12=(a12-a14);
  if (res[0]!=0) res[0][3]=a12;
  a12=arg[4]? arg[4][93] : 0;
  a14=(a12*a1);
  a15=arg[4]? arg[4][94] : 0;
  a16=(a15*a6);
  a14=(a14+a16);
  a16=arg[4]? arg[4][95] : 0;
  a16=(a16+a8);
  a14=(a14-a16);
  if (res[0]!=0) res[0][4]=a14;
  a14=arg[4]? arg[4][96] : 0;
  a16=(a14*a1);
  a17=arg[4]? arg[4][97] : 0;
  a18=(a17*a6);
  a16=(a16+a18);
  a18=arg[4]? arg[4][98] : 0;
  a18=(a18+a8);
  a16=(a16-a18);
  if (res[0]!=0) res[0][5]=a16;
  a16=arg[4]? arg[4][99] : 0;
  a18=(a16*a1);
  a19=arg[4]? arg[4][100] : 0;
  a20=(a19*a6);
  a18=(a18+a20);
  a20=arg[4]? arg[4][101] : 0;
  a20=(a20+a8);
  a18=(a18-a20);
  if (res[0]!=0) res[0][6]=a18;
  a18=arg[4]? arg[4][102] : 0;
  a20=(a18*a1);
  a21=arg[4]? arg[4][103] : 0;
  a22=(a21*a6);
  a20=(a20+a22);
  a22=arg[4]? arg[4][104] : 0;
  a22=(a22+a8);
  a20=(a20-a22);
  if (res[0]!=0) res[0][7]=a20;
  a20=arg[4]? arg[4][105] : 0;
  a22=(a20*a1);
  a23=arg[4]? arg[4][106] : 0;
  a24=(a23*a6);
  a22=(a22+a24);
  a24=arg[4]? arg[4][107] : 0;
  a24=(a24+a8);
  a22=(a22-a24);
  if (res[0]!=0) res[0][8]=a22;
  a22=arg[4]? arg[4][108] : 0;
  a24=(a22*a1);
  a25=arg[4]? arg[4][109] : 0;
  a26=(a25*a6);
  a24=(a24+a26);
  a26=arg[4]? arg[4][110] : 0;
  a26=(a26+a8);
  a24=(a24-a26);
  if (res[0]!=0) res[0][9]=a24;
  a24=arg[4]? arg[4][111] : 0;
  a26=(a24*a1);
  a27=arg[4]? arg[4][112] : 0;
  a28=(a27*a6);
  a26=(a26+a28);
  a28=arg[4]? arg[4][113] : 0;
  a28=(a28+a8);
  a26=(a26-a28);
  if (res[0]!=0) res[0][10]=a26;
  a26=arg[4]? arg[4][114] : 0;
  a1=(a26*a1);
  a28=arg[4]? arg[4][115] : 0;
  a6=(a28*a6);
  a1=(a1+a6);
  a6=arg[4]? arg[4][116] : 0;
  a6=(a6+a8);
  a1=(a1-a6);
  if (res[0]!=0) res[0][11]=a1;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a5;
  a1=cos(a2);
  a1=(a4*a1);
  a6=(a5*a1);
  a8=sin(a2);
  a8=(a4*a8);
  a29=(a0*a8);
  a6=(a6-a29);
  if (res[1]!=0) res[1][2]=a6;
  a6=-1.;
  if (res[1]!=0) res[1][3]=a6;
  if (res[1]!=0) res[1][4]=a3;
  if (res[1]!=0) res[1][5]=a9;
  a29=(a9*a1);
  a30=(a3*a8);
  a29=(a29-a30);
  if (res[1]!=0) res[1][6]=a29;
  if (res[1]!=0) res[1][7]=a6;
  if (res[1]!=0) res[1][8]=a7;
  if (res[1]!=0) res[1][9]=a11;
  a29=(a11*a1);
  a30=(a7*a8);
  a29=(a29-a30);
  if (res[1]!=0) res[1][10]=a29;
  if (res[1]!=0) res[1][11]=a6;
  if (res[1]!=0) res[1][12]=a10;
  if (res[1]!=0) res[1][13]=a13;
  a29=(a13*a1);
  a30=(a10*a8);
  a29=(a29-a30);
  if (res[1]!=0) res[1][14]=a29;
  if (res[1]!=0) res[1][15]=a6;
  if (res[1]!=0) res[1][16]=a12;
  if (res[1]!=0) res[1][17]=a15;
  a29=(a15*a1);
  a30=(a12*a8);
  a29=(a29-a30);
  if (res[1]!=0) res[1][18]=a29;
  if (res[1]!=0) res[1][19]=a6;
  if (res[1]!=0) res[1][20]=a14;
  if (res[1]!=0) res[1][21]=a17;
  a29=(a17*a1);
  a30=(a14*a8);
  a29=(a29-a30);
  if (res[1]!=0) res[1][22]=a29;
  if (res[1]!=0) res[1][23]=a6;
  if (res[1]!=0) res[1][24]=a16;
  if (res[1]!=0) res[1][25]=a19;
  a29=(a19*a1);
  a30=(a16*a8);
  a29=(a29-a30);
  if (res[1]!=0) res[1][26]=a29;
  if (res[1]!=0) res[1][27]=a6;
  if (res[1]!=0) res[1][28]=a18;
  if (res[1]!=0) res[1][29]=a21;
  a29=(a21*a1);
  a30=(a18*a8);
  a29=(a29-a30);
  if (res[1]!=0) res[1][30]=a29;
  if (res[1]!=0) res[1][31]=a6;
  if (res[1]!=0) res[1][32]=a20;
  if (res[1]!=0) res[1][33]=a23;
  a29=(a23*a1);
  a30=(a20*a8);
  a29=(a29-a30);
  if (res[1]!=0) res[1][34]=a29;
  if (res[1]!=0) res[1][35]=a6;
  if (res[1]!=0) res[1][36]=a22;
  if (res[1]!=0) res[1][37]=a25;
  a29=(a25*a1);
  a30=(a22*a8);
  a29=(a29-a30);
  if (res[1]!=0) res[1][38]=a29;
  if (res[1]!=0) res[1][39]=a6;
  if (res[1]!=0) res[1][40]=a24;
  if (res[1]!=0) res[1][41]=a27;
  a29=(a27*a1);
  a30=(a24*a8);
  a29=(a29-a30);
  if (res[1]!=0) res[1][42]=a29;
  if (res[1]!=0) res[1][43]=a6;
  if (res[1]!=0) res[1][44]=a26;
  if (res[1]!=0) res[1][45]=a28;
  a1=(a28*a1);
  a8=(a26*a8);
  a1=(a1-a8);
  if (res[1]!=0) res[1][46]=a1;
  if (res[1]!=0) res[1][47]=a6;
  a6=arg[2]? arg[2][11] : 0;
  a28=(a28*a6);
  a1=arg[2]? arg[2][10] : 0;
  a27=(a27*a1);
  a28=(a28+a27);
  a27=arg[2]? arg[2][9] : 0;
  a25=(a25*a27);
  a28=(a28+a25);
  a25=arg[2]? arg[2][8] : 0;
  a23=(a23*a25);
  a28=(a28+a23);
  a23=arg[2]? arg[2][7] : 0;
  a21=(a21*a23);
  a28=(a28+a21);
  a21=arg[2]? arg[2][6] : 0;
  a19=(a19*a21);
  a28=(a28+a19);
  a19=arg[2]? arg[2][5] : 0;
  a17=(a17*a19);
  a28=(a28+a17);
  a17=arg[2]? arg[2][4] : 0;
  a15=(a15*a17);
  a28=(a28+a15);
  a15=arg[2]? arg[2][3] : 0;
  a13=(a13*a15);
  a28=(a28+a13);
  a13=arg[2]? arg[2][2] : 0;
  a11=(a11*a13);
  a28=(a28+a11);
  a11=arg[2]? arg[2][1] : 0;
  a9=(a9*a11);
  a28=(a28+a9);
  a9=arg[2]? arg[2][0] : 0;
  a5=(a5*a9);
  a28=(a28+a5);
  a28=(a4*a28);
  a5=sin(a2);
  a28=(a28*a5);
  a26=(a26*a6);
  a24=(a24*a1);
  a26=(a26+a24);
  a22=(a22*a27);
  a26=(a26+a22);
  a20=(a20*a25);
  a26=(a26+a20);
  a18=(a18*a23);
  a26=(a26+a18);
  a16=(a16*a21);
  a26=(a26+a16);
  a14=(a14*a19);
  a26=(a26+a14);
  a12=(a12*a17);
  a26=(a26+a12);
  a10=(a10*a15);
  a26=(a26+a10);
  a7=(a7*a13);
  a26=(a26+a7);
  a3=(a3*a11);
  a26=(a26+a3);
  a0=(a0*a9);
  a26=(a26+a0);
  a4=(a4*a26);
  a2=cos(a2);
  a4=(a4*a2);
  a28=(a28+a4);
  a28=(-a28);
  if (res[2]!=0) res[2][0]=a28;
  return 0;
}

CASADI_SYMBOL_EXPORT int Solver_constr_h_fun_jac_uxt_zt_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Solver_constr_h_fun_jac_uxt_zt_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Solver_constr_h_fun_jac_uxt_zt_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Solver_constr_h_fun_jac_uxt_zt_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Solver_constr_h_fun_jac_uxt_zt_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Solver_constr_h_fun_jac_uxt_zt_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Solver_constr_h_fun_jac_uxt_zt_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Solver_constr_h_fun_jac_uxt_zt_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Solver_constr_h_fun_jac_uxt_zt_hess_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int Solver_constr_h_fun_jac_uxt_zt_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real Solver_constr_h_fun_jac_uxt_zt_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Solver_constr_h_fun_jac_uxt_zt_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Solver_constr_h_fun_jac_uxt_zt_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Solver_constr_h_fun_jac_uxt_zt_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Solver_constr_h_fun_jac_uxt_zt_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Solver_constr_h_fun_jac_uxt_zt_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
